### ISSUE TITLE
cargo-lambda-watch does not compile with rust 1.66.1

### ISSUE THREAD

**Issue by michaetto** [cargo-lambda/cargo-lambda#325]
$ cargo --version
cargo 1.66.1 (ad779e08b 2023-01-10)
$ cargo install cargo-lambda
...
   Compiling cargo-lambda-watch v0.14.0
error[E0308]: mismatched types
   --> /home/michal/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-lambda-watch-0.14.0/src/watcher.rs:65:40
    |
65  |             .add_globs(&["**/*"], Some(wc.base))
    |                                   ---- ^^^^^^^
    |                                   |    |
    |                                   |    expected `&PathBuf`, found struct `PathBuf`
    |                                   |    help: consider borrowing here: `&wc.base`
    |                                   arguments to this enum variant are incorrect
    |
note: tuple variant defined here
   --> /home/michal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:526:5
    |
526 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error[E0277]: `Result<(), ignore_files::Error>` is not a future
  --> /home/michal/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-lambda-watch-0.14.0/src/watcher.rs:66:13
   |
66 |             .await
   |             ^^^^^^
   |             |
   |             `Result<(), ignore_files::Error>` is not a future
   |             help: remove the `.await`
   |
   = help: the trait `Future` is not implemented for `Result<(), ignore_files::Error>`
   = note: Result<(), ignore_files::Error> must be a future or must implement `IntoFuture` to be awaited
   = note: required for `Result<(), ignore_files::Error>` to implement `IntoFuture`

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `cargo-lambda-watch` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-lambda v0.14.0`, intermediate artifacts can be found at `/tmp/cargo-installUJJaQY`
